[package]
name = "forward"
version = "0.1.0"
authors = ["Owain Lewis <owain.lewis@oracle.com>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.11"
env_logger = "0.8.1"
hyper-tls = "0.5.0"