[package]
name = "forward"
version = "0.1.0"
authors = ["Owain Lewis <owain.lewis@oracle.com>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }